export const WC2026_GROUPS: Record<
  string,
  {
    name: string;
    country: string;
    flagCode: string;
    fbrefId: string;
    fbrefUrl: string;
  }[]
> = {
  A: [
    {
      name: 'Mexico',
      country: 'Mexico',
      flagCode: 'mx',
      fbrefId: 'b009a548',
      fbrefUrl: 'https://fbref.com/en/squads/b009a548/Mexico-Men-Stats',
    },
    {
      name: 'South Africa',
      country: 'South Africa',
      flagCode: 'za',
      fbrefId: '506f1741',
      fbrefUrl: 'https://fbref.com/en/squads/506f1741/South-Africa-Men-Stats',
    },
    {
      name: 'Korea Republic',
      country: 'Korea Republic',
      flagCode: 'kr',
      fbrefId: '473f0fbf',
      fbrefUrl: 'https://fbref.com/en/squads/473f0fbf/Korea-Republic-Men-Stats',
    },
    {
      name: 'Czechia',
      country: 'Czechia',
      flagCode: 'cz',
      fbrefId: '2740937c',
      fbrefUrl: 'https://fbref.com/en/squads/2740937c/Czechia-Men-Stats',
    },
  ],
  B: [
    {
      name: 'Canada',
      country: 'Canada',
      flagCode: 'ca',
      fbrefId: '9c6d90a0',
      fbrefUrl: 'https://fbref.com/en/squads/9c6d90a0/Canada-Men-Stats',
    },
    {
      name: 'Bosnia and Herzegovina',
      country: 'Bosnia and Herzegovina',
      flagCode: 'ba',
      fbrefId: '6c5ef1c3',
      fbrefUrl:
        'https://fbref.com/en/squads/6c5ef1c3/Bosnia-and-Herzegovina-Men-Stats',
    },
    {
      name: 'Qatar',
      country: 'Qatar',
      flagCode: 'qa',
      fbrefId: '9b696ed1',
      fbrefUrl: 'https://fbref.com/en/squads/9b696ed1/Qatar-Men-Stats',
    },
    {
      name: 'Switzerland',
      country: 'Switzerland',
      flagCode: 'ch',
      fbrefId: '81021a70',
      fbrefUrl: 'https://fbref.com/en/squads/81021a70/Switzerland-Men-Stats',
    },
  ],
  C: [
    {
      name: 'Brazil',
      country: 'Brazil',
      flagCode: 'br',
      fbrefId: '304635c3',
      fbrefUrl: 'https://fbref.com/en/squads/304635c3/Brazil-Men-Stats',
    },
    {
      name: 'Morocco',
      country: 'Morocco',
      flagCode: 'ma',
      fbrefId: 'af41ccda',
      fbrefUrl: 'https://fbref.com/en/squads/af41ccda/Morocco-Men-Stats',
    },
    {
      name: 'Haiti',
      country: 'Haiti',
      flagCode: 'ht',
      fbrefId: '61828292',
      fbrefUrl: 'https://fbref.com/en/squads/61828292/Haiti-Men-Stats',
    },
    {
      name: 'Scotland',
      country: 'Scotland',
      flagCode: 'gb-sct',
      fbrefId: '602d3994',
      fbrefUrl: 'https://fbref.com/en/squads/602d3994/Scotland-Men-Stats',
    },
  ],
  D: [
    {
      name: 'United States',
      country: 'United States',
      flagCode: 'us',
      fbrefId: '0f66725b',
      fbrefUrl: 'https://fbref.com/en/squads/0f66725b/United-States-Men-Stats',
    },
    {
      name: 'Paraguay',
      country: 'Paraguay',
      flagCode: 'py',
      fbrefId: 'd2043442',
      fbrefUrl: 'https://fbref.com/en/squads/d2043442/Paraguay-Men-Stats',
    },
    {
      name: 'Australia',
      country: 'Australia',
      flagCode: 'au',
      fbrefId: 'b90bf4f9',
      fbrefUrl: 'https://fbref.com/en/squads/b90bf4f9/Australia-Men-Stats',
    },
    {
      name: 'Turkiye',
      country: 'Turkiye',
      flagCode: 'tr',
      fbrefId: 'ac6bcf92',
      fbrefUrl: 'https://fbref.com/en/squads/ac6bcf92/Turkiye-Men-Stats',
    },
  ],
  E: [
    {
      name: 'Germany',
      country: 'Germany',
      flagCode: 'de',
      fbrefId: 'c1e40422',
      fbrefUrl: 'https://fbref.com/en/squads/c1e40422/Germany-Men-Stats',
    },
    {
      name: 'Curacao',
      country: 'Curacao',
      flagCode: 'cw',
      fbrefId: 'e0f5893a',
      fbrefUrl: 'https://fbref.com/en/squads/e0f5893a/Curacao-Men-Stats',
    },
    {
      name: "Cote d'Ivoire",
      country: "Cote d'Ivoire",
      flagCode: 'ci',
      fbrefId: '24772b12',
      fbrefUrl: 'https://fbref.com/en/squads/24772b12/Cote-dIvoire-Men-Stats',
    },
    {
      name: 'Ecuador',
      country: 'Ecuador',
      flagCode: 'ec',
      fbrefId: '123acaf8',
      fbrefUrl: 'https://fbref.com/en/squads/123acaf8/Ecuador-Men-Stats',
    },
  ],
  F: [
    {
      name: 'Netherlands',
      country: 'Netherlands',
      flagCode: 'nl',
      fbrefId: '5bb5024a',
      fbrefUrl: 'https://fbref.com/en/squads/5bb5024a/Netherlands-Men-Stats',
    },
    {
      name: 'Japan',
      country: 'Japan',
      flagCode: 'jp',
      fbrefId: 'ffcf1690',
      fbrefUrl: 'https://fbref.com/en/squads/ffcf1690/Japan-Men-Stats',
    },
    {
      name: 'Sweden',
      country: 'Sweden',
      flagCode: 'se',
      fbrefId: '296f69e7',
      fbrefUrl: 'https://fbref.com/en/squads/296f69e7/Sweden-Men-Stats',
    },
    {
      name: 'Tunisia',
      country: 'Tunisia',
      flagCode: 'tn',
      fbrefId: 'a7c7562a',
      fbrefUrl: 'https://fbref.com/en/squads/a7c7562a/Tunisia-Men-Stats',
    },
  ],
  G: [
    {
      name: 'Belgium',
      country: 'Belgium',
      flagCode: 'be',
      fbrefId: '361422b9',
      fbrefUrl: 'https://fbref.com/en/squads/361422b9/Belgium-Men-Stats',
    },
    {
      name: 'Egypt',
      country: 'Egypt',
      flagCode: 'eg',
      fbrefId: 'b8889750',
      fbrefUrl: 'https://fbref.com/en/squads/b8889750/Egypt-Men-Stats',
    },
    {
      name: 'IR Iran',
      country: 'IR Iran',
      flagCode: 'ir',
      fbrefId: '6a08f71e',
      fbrefUrl: 'https://fbref.com/en/squads/6a08f71e/IR-Iran-Men-Stats',
    },
    {
      name: 'New Zealand',
      country: 'New Zealand',
      flagCode: 'nz',
      fbrefId: '259855f0',
      fbrefUrl: 'https://fbref.com/en/squads/259855f0/New-Zealand-Men-Stats',
    },
  ],
  H: [
    {
      name: 'Spain',
      country: 'Spain',
      flagCode: 'es',
      fbrefId: 'b561dd30',
      fbrefUrl: 'https://fbref.com/en/squads/b561dd30/Spain-Men-Stats',
    },
    {
      name: 'Cape Verde',
      country: 'Cape Verde',
      flagCode: 'cv',
      fbrefId: '31fa6fa6',
      fbrefUrl: 'https://fbref.com/en/squads/31fa6fa6/Cape-Verde-Men-Stats',
    },
    {
      name: 'Saudi Arabia',
      country: 'Saudi Arabia',
      flagCode: 'sa',
      fbrefId: '6e84edac',
      fbrefUrl: 'https://fbref.com/en/squads/6e84edac/Saudi-Arabia-Men-Stats',
    },
    {
      name: 'Uruguay',
      country: 'Uruguay',
      flagCode: 'uy',
      fbrefId: '870e020f',
      fbrefUrl: 'https://fbref.com/en/squads/870e020f/Uruguay-Men-Stats',
    },
  ],
  I: [
    {
      name: 'France',
      country: 'France',
      flagCode: 'fr',
      fbrefId: 'b1b36dcd',
      fbrefUrl: 'https://fbref.com/en/squads/b1b36dcd/France-Men-Stats',
    },
    {
      name: 'Senegal',
      country: 'Senegal',
      flagCode: 'sn',
      fbrefId: '9ab5c684',
      fbrefUrl: 'https://fbref.com/en/squads/9ab5c684/Senegal-Men-Stats',
    },
    {
      name: 'Iraq',
      country: 'Iraq',
      flagCode: 'iq',
      fbrefId: 'ec843efd',
      fbrefUrl: 'https://fbref.com/en/squads/ec843efd/Iraq-Men-Stats',
    },
    {
      name: 'Norway',
      country: 'Norway',
      flagCode: 'no',
      fbrefId: '599eba19',
      fbrefUrl: 'https://fbref.com/en/squads/599eba19/Norway-Men-Stats',
    },
  ],
  J: [
    {
      name: 'Argentina',
      country: 'Argentina',
      flagCode: 'ar',
      fbrefId: 'f9fddd6e',
      fbrefUrl: 'https://fbref.com/en/squads/f9fddd6e/Argentina-Men-Stats',
    },
    {
      name: 'Algeria',
      country: 'Algeria',
      flagCode: 'dz',
      fbrefId: '1e2dba57',
      fbrefUrl: 'https://fbref.com/en/squads/1e2dba57/Algeria-Men-Stats',
    },
    {
      name: 'Austria',
      country: 'Austria',
      flagCode: 'at',
      fbrefId: 'd5121f10',
      fbrefUrl: 'https://fbref.com/en/squads/d5121f10/Austria-Men-Stats',
    },
    {
      name: 'Jordan',
      country: 'Jordan',
      flagCode: 'jo',
      fbrefId: '3e22f0fa',
      fbrefUrl: 'https://fbref.com/en/squads/3e22f0fa/Jordan-Men-Stats',
    },
  ],
  K: [
    {
      name: 'Portugal',
      country: 'Portugal',
      flagCode: 'pt',
      fbrefId: '4a1b4ea8',
      fbrefUrl: 'https://fbref.com/en/squads/4a1b4ea8/Portugal-Men-Stats',
    },
    {
      name: 'Congo DR',
      country: 'Congo DR',
      flagCode: 'cd',
      fbrefId: '9be9f315',
      fbrefUrl: 'https://fbref.com/en/squads/9be9f315/Congo-DR-Men-Stats',
    },
    {
      name: 'Uzbekistan',
      country: 'Uzbekistan',
      flagCode: 'uz',
      fbrefId: 'cd389e75',
      fbrefUrl: 'https://fbref.com/en/squads/cd389e75/Uzbekistan-Men-Stats',
    },
    {
      name: 'Colombia',
      country: 'Colombia',
      flagCode: 'co',
      fbrefId: 'ab73cfe5',
      fbrefUrl: 'https://fbref.com/en/squads/ab73cfe5/Colombia-Men-Stats',
    },
  ],
  L: [
    {
      name: 'England',
      country: 'England',
      flagCode: 'gb-eng',
      fbrefId: '1862c019',
      fbrefUrl: 'https://fbref.com/en/squads/1862c019/England-Men-Stats',
    },
    {
      name: 'Croatia',
      country: 'Croatia',
      flagCode: 'hr',
      fbrefId: '7b08e376',
      fbrefUrl: 'https://fbref.com/en/squads/7b08e376/Croatia-Men-Stats',
    },
    {
      name: 'Ghana',
      country: 'Ghana',
      flagCode: 'gh',
      fbrefId: '9349828d',
      fbrefUrl: 'https://fbref.com/en/squads/9349828d/Ghana-Men-Stats',
    },
    {
      name: 'Panama',
      country: 'Panama',
      flagCode: 'pa',
      fbrefId: '6061a82d',
      fbrefUrl: 'https://fbref.com/en/squads/6061a82d/Panama-Men-Stats',
    },
  ],
};

export const FIFA_RANKINGS: Record<string, number> = {
  Argentina: 1,
  France: 2,
  England: 3,
  Belgium: 4,
  Brazil: 5,
  Portugal: 6,
  Netherlands: 7,
  Spain: 8,
  Germany: 9,
  Morocco: 10,
  Japan: 11,
  Canada: 14,
  Croatia: 15,
  Mexico: 16,
  'United States': 16,
  Switzerland: 17,
  Senegal: 18,
  Colombia: 19,
  Uruguay: 20,
  Denmark: 21,
  'Korea Republic': 22,
  'IR Iran': 23,
  Australia: 23,
  Sweden: 25,
  Norway: 26,
  Turkiye: 27,
  Austria: 28,
  Ecuador: 33,
  Egypt: 34,
  Czechia: 36,
  Qatar: 37,
  Scotland: 39,
  Tunisia: 42,
  Panama: 43,
  "Cote d'Ivoire": 47,
  Algeria: 48,
  Paraguay: 53,
  'Saudi Arabia': 56,
  'Congo DR': 57,
  'South Africa': 59,
  'Bosnia and Herzegovina': 60,
  Ghana: 63,
  Jordan: 65,
  Iraq: 68,
  Uzbekistan: 70,
  'Cape Verde': 76,
  Curacao: 81,
  Haiti: 84,
  'New Zealand': 102,
};
